name: Java CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: eroshenkoam/github-action
        volumes:
          - /builds:/builds
    steps:
    - uses: actions/checkout@v1
    - name: Printn service env
      run: cat /builds/env
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew test
